#! /usr/bin/env bash

echo "Cleaning up everything:"
pushd infra
cluster_name=$(cat input.tfvars | grep "cluster_name" | awk -F= '/=/{gsub(/ /, "", $0); print $2}' | tr -d '"')
namespace=$(cat input.tfvars | grep "namespace" | awk -F= '/=/{gsub(/ /, "", $0); print $2}' | tr -d '"')
docker_image=$(cat input.tfvars | grep "app_name" | awk -F= '/=/{gsub(/ /, "", $0); print $2}' | tr -d '"')

helm delete ${docker_image} -n ${namespace} && \
helm delete aws-load-balancer-controller -n kube-system
echo "Waiting for a minute for all pods to terminate and remove dependencies..."
sleep 60

echo "Deleting security groups generated by ALB:"
k8s_security_groups=$(aws ec2 describe-security-groups --filter Name=tag:elbv2.k8s.aws/cluster,Values=${cluster_name} --query "SecurityGroups[].GroupId" --output text)
for sg in ${k8s_security_groups}; do
  echo "  Security group Id: $sg"
  aws ec2 delete-security-group --group-id ${sg}
done
echo "Done."

terraform destroy -var-file="input.tfvars" -auto-approve
popd
