apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: init-runners
  namespace: actions-runners
spec:
  template:
    spec:
      repository: liatrio-enterprise/codeql-examples
      labels:
        - codeql
        - dependabot
      containers:
      - name: runner
        resources:
          limits:
            cpu: "1.0"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
      - name: docker
        resources:
          limits:
            cpu: "1.0"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: init-runners-autoscaler
  namespace: actions-runners
annotations:
  "helm.sh/hook": post-install,post-upgrade
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: init-runners
  minReplicas: 3
  maxReplicas: 30
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: "0.66"
      scaleDownThreshold: "0.33"
      scaleUpFactor: "2"
      scaleDownFactor: "0.5"
