repositories:
  - name: cert-manager
    url: https://charts.jetstack.io

  - name: autoscaler
    url: https://kubernetes.github.io/autoscaler

  - name: actions-runner-controller
    url: https://actions-runner-controller.github.io/actions-runner-controller

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.11.0

  - name: autoscaler
    namespace: kube-system
    chart: autoscaler/cluster-autoscaler
    version: 9.26.0
    set:
      - name: cloudProvider
        value: aws
      - name: autoDiscovery.clusterName
        value: "ghest"

  - name: actions-runner-controller
    namespace: actions-runners
    createNamespace: true
    chart: actions-runner-controller/actions-runner-controller
    version: 0.22.0
    set:
      - name: authSecret.github_app_id
        value: {{requiredEnv "GITHUB_APP_ID"}}
      - name: authSecret.github_app_installation_id
        value: {{requiredEnv "GITHUB_APP_INSTALLATION_ID"}}
      - name: authSecret.github_app_private_key
        value: {{requiredEnv "GITHUB_APP_PRIVATE_KEY"}}
