repositories:
  - name: autoscaler
    url: https://kubernetes.github.io/autoscaler

  - name: jetstack
    url: https://charts.jetstack.io

  - name: actions-runner-controller
    url: https://actions-runner-controller.github.io/actions-runner-controller

releases:
  - name: autoscaler
    namespace: kube-system
    chart: autoscaler/cluster-autoscaler
    version: 9.26.0
    set:
      - name: cloudProvider
        value: aws
      - name: autoDiscovery.clusterName
        value: "ghest"

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.11.0
    wait: true
    waitForJobs: true
    set:
      - name: installCRDs
        value: true

  - name: actions-runner-controller
    namespace: actions-runners
    createNamespace: true
    chart: actions-runner-controller/actions-runner-controller
    version: 0.22.0
    wait: true
    disableValidationOnInstall: true
    set:
      - name: authSecret.create
        value: true
    needs:
      - cert-manager/cert-manager
