---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ .Values.name }}-autoscaler
  namespace: {{ .Values.namespace }}
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: init-runners
  minReplicas: {{ .Values.replicas.min }}
  maxReplicas: {{ .Values.replicas.max }}
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: {{ .Values.autoscaling.scaleUpThreshold }}
      scaleDownThreshold: {{ .Values.autoscaling.scaleDownThreshold }}
      scaleUpFactor: {{ .Values.autoscaling.scaleUpFactor }}
      scaleDownFactor: {{ .Values.autoscaling.scaleDownFactor }}
