name: Create EKS Cluster

on:
  push:
    branches: [ 'main' ]
    paths:
      - "**/aws/**"
      - ".github/workflows/aws-terraform.yml"
  pull_request:
    branches: [ 'main' ]
    paths:
      - "**/aws/**"
      - ".github/workflows/aws-terraform.yml"

jobs:
  create:
    name: Create EKS Cluster
    uses: ./.github/workflows/create-cluster.yml
    secrets: inherit
    with:
      cloud_provider: aws
      config_path: infra/live/aws/linux-public/
