name: Create AKS Cluster

on:
  push:
    branches: [ 'main' ]
    paths:
      - "**/azure/**"
      - ".github/workflows/azure-terraform.yml"
  pull_request:
    branches: [ 'main' ]
    paths:
      - "**/azure/**"
      - ".github/workflows/azure-terraform.yml"

jobs:
  create:
    name: Create AKS Cluster
    uses: ./.github/workflows/create-cluster.yml
    secrets: inherit
    with:
      cloud_provider: azure
      config_path: infra/live/azure/linux-public/
