# workflow to deploy kubernetes manifest to eks cluster using aws-eks-deploy action
name: Deploy to EKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint all YAML files
        run: |
          yamllint .

      - name: Deploy to EKS
        uses: aws-actions/amazon-eks-deploy-kubernetes-manifest@v1
        with:
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          manifest: ${{ secrets.MANIFEST }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}