name: "Generate terraform docs"
on:
    pull_request:
        branches:
            - main
jobs:
  update-docs:
    name: Update Terraform module documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
            find-dir: ./infra/modules,./infra/src
            output-method: replace
            git-push: true
