name: "Generate terraform docs"
on:
    pull_request:
permissions:
    contents: write
jobs:
  update-docs:
    name: Update Terraform module documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
            ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
            find-dir: ./infra
            output-method: inject
            git-push: true
