name: "Generate terraform docs"
on:
    push:
        branches:
            - main

jobs:
  update-docs:
    name: Update Terraform module documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
            find-dir: ./infra/modules
            output-method: replace
